services:
  zookeeper:
    platform: linux/amd64
    image: confluentinc/cp-zookeeper:4.1.1   # kafka 1.1.1
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    platform: linux/amd64
    image: confluentinc/cp-kafka:4.1.1   # kafka 1.1.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=600000
    # workaround for okteto stack deploy -- https://github.com/confluentinc/schema-registry/issues/689
    command: ["bash", "-c", "unset KAFKA_PORT && /etc/confluent/docker/run"]
    depends_on:
      - zookeeper

  kafka-manager:
    platform: linux/amd64
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    depends_on:
      - zookeeper
